# Project Name
TARGET = MIDI_USB_Baseline

# Sources
CPP_SOURCES = MIDI_USB_Baseline.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
