# Project Name
TARGET = MIDI2_Device_Synth

# Sources
CPP_SOURCES = MIDI2_Device_Synth.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
